# site-prefixed variables

title: JETS Technologies, LLC.
logo:
  url: https://avatars0.githubusercontent.com/u/12983669?s=200&v=4
  alt: JETS Tech Logo
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

page_categories:
  - engineering
  - design
  - process
